// <auto-generated />
namespace WorlHospital.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class patientRegLogContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(patientRegLogContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201506011235186_patientRegLogContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
